//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public int ID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string Token1 { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
