//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBankAccount
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string AccountNo { get; set; }
        public Nullable<byte> AccountTypeID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> CurrentBalance { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
