//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTransaction
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<byte> TransactionTypeID { get; set; }
        public Nullable<decimal> CRAmount { get; set; }
        public Nullable<decimal> DRAmount { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Remark { get; set; }
    
        public virtual TransactionType TransactionType { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
